<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>MarkerOne.Conformance</AssemblyName>
    <RootNamespace>MarkerOne.Conformance</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MarkerOne.Core/MarkerOne.Core.csproj" />
  </ItemGroup>

</Project>
