/* Firebase project settings.
 *
 * The web API key is not a secret. It identifies the project to Google's
 * endpoints; it authorises nothing. Anyone can read it out of any Firebase web
 * app, which is why what actually protects the data is firestore.rules, plus
 * App Check to make abuse cost something. Committing it is correct — treating
 * it as a credential is the mistake.
 *
 * Leave projectId empty and the app runs exactly as it did before: local
 * content.json, no network, no accounts.
 *
 * Do not edit this file with your own settings — put them in
 * spatial/config.local.js, which is gitignored and loaded after this one:
 *
 *   SpatialConfig.override({ projectId: 'your-project', apiKey: 'AIza…' });
 *
 * That keeps your project out of version control and, more to the point,
 * keeps every future pull from conflicting with it.
 */
(function (root) {
  'use strict';

  root.SpatialConfig = {
    projectId: '',                 // e.g. 'markerone1965'
    apiKey: '',                    // Project settings -> Your apps -> Web API Key

    // Placements further than this from the viewer are not fetched. Loading a
    // city's worth of content to render the three things you can actually see
    // is the obvious mistake.
    radiusM: 300,

    // How far the device may travel before the local-to-global transform is
    // re-derived. WebXR tracking drifts, slowly and without saying so.
    relocalizeAfterM: 25,

    /* App Check. Off unless all three are filled in.
     *
     * Anonymous auth costs an attacker one request and rules cannot
     * rate-limit, so this is what makes writing expensive. It is also the one
     * part of this project that loads a script from another origin —
     * reCAPTCHA has to run Google's code from Google's servers — so it is
     * opt-in rather than assumed.
     *
     * projectNumber is the *number* from project settings, not the project
     * id. They are different and the wrong one returns a bare 404.
     */
    appCheck: {
      // 'v3' for a classic key from google.com/recaptcha/admin;
      // 'enterprise' for one from the Google Cloud console, which lists it
      // with an "ID" and a type of "Website / Score". Two products, two
      // scripts, two exchange endpoints, one name.
      provider: 'v3',
      projectNumber: '',
      appId: '',                   // 1:123...:web:abc...
      recaptchaSiteKey: ''
    }
  };

  // Applied by spatial/config.local.js if it exists. Shallow by design: the
  // settings are flat, and a deep merge would only make it harder to see what
  // a local override actually changed.
  root.SpatialConfig.override = function (settings) {
    Object.keys(settings || {}).forEach(function (key) {
      root.SpatialConfig[key] = settings[key];
    });
    root.SpatialConfig.enabled = ready(root.SpatialConfig);
    return root.SpatialConfig;
  };

  function ready(c) { return !!(c.projectId && c.apiKey); }

  root.SpatialConfig.enabled = ready(root.SpatialConfig);
}(typeof self !== 'undefined' ? self : this));
