/* Conformance vectors for the native port.
 *
 * The geodesy in spatial/ has a hundred-odd assertions behind it and two
 * corrected sign errors in its history — a mirrored render frame and a
 * quaternion pointing the wrong way — neither of which announced itself as
 * anything other than "the world is subtly wrong". Rewriting that in C# by
 * hand and hoping is not a plan.
 *
 * So the trusted implementation emits its own answers here, and the port is
 * checked against them. Same inputs, same outputs, to a tolerance, or the
 * build fails. Regenerate whenever spatial/geo.js or spatial/localize.js
 * changes:
 *
 *   node scripts/make-vectors.mjs
 */

import { createRequire } from 'node:module';
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const require = createRequire(import.meta.url);
const geo = require(join(ROOT, 'spatial', 'geo.js'));
const localize = require(join(ROOT, 'spatial', 'localize.js'));

// Deterministic: the vectors are committed, and a diff should mean the maths
// changed rather than that the dice rolled differently.
let seed = 0x2F6E2B1;
const rnd = () => {
  seed ^= seed << 13; seed >>>= 0;
  seed ^= seed >> 17;
  seed ^= seed << 5; seed >>>= 0;
  return seed / 0x100000000;
};
const between = (lo, hi) => lo + rnd() * (hi - lo);

/* Places chosen to cover the things that break: both hemispheres, both sides
   of the meridian, high latitude where longitude collapses, the equator, and
   heights well above and slightly below the ellipsoid. */
const PLACES = [
  { lat: 51.5007, lon: -0.1246, h: 35 },
  { lat: -33.8568, lon: 151.2153, h: 0 },
  { lat: 64.1466, lon: -21.9426, h: 120 },
  { lat: -54.8019, lon: -68.3030, h: 5 },
  { lat: 0.3476, lon: 32.5825, h: 1190 },
  { lat: 78.2232, lon: 15.6267, h: 10 },
  { lat: -0.0001, lon: 179.9, h: -30 },
  { lat: 35.6762, lon: 139.6503, h: 40 }
];

const round = (n) => Number(n.toFixed(9));

const vectors = {
  '//': 'Generated by scripts/make-vectors.mjs from spatial/geo.js and spatial/localize.js. Do not edit.',
  generatedFrom: 'spatial/geo.js, spatial/localize.js',

  ecef: PLACES.map((p) => ({
    input: p,
    ecef: mapValues(geo.toEcef(p.lat, p.lon, p.h), round),
    roundTrip: mapValues(geo.fromEcef(...Object.values(geo.toEcef(p.lat, p.lon, p.h))), round)
  })),

  enu: [],
  render: [],
  heading: [],
  quaternion: [],
  distance: [],
  geohash: [],
  bounds: [],
  frame: [],
  baseline: [],
  origin: []
};

/* ── ENU about each origin, at a spread of offsets ────────── */
for (const origin of PLACES) {
  for (let i = 0; i < 8; i++) {
    const target = {
      lat: clampLat(origin.lat + between(-0.02, 0.02)),
      lon: wrapLon(origin.lon + between(-0.02, 0.02)),
      h: origin.h + between(-60, 60)
    };
    const enu = geo.toEnu(target.lat, target.lon, target.h, origin);
    vectors.enu.push({
      origin,
      target,
      enu: mapValues(enu, round),
      back: mapValues(geo.fromEnu(enu.e, enu.n, enu.u, origin), round)
    });
  }
}

/* ── render frame ─────────────────────────────────────────── */
for (let i = 0; i < 24; i++) {
  const enu = { e: between(-500, 500), n: between(-500, 500), u: between(-50, 50) };
  vectors.render.push({
    enu: mapValues(enu, round),
    three: mapValues(geo.enuToThree(enu), round)
  });
}

/* ── headings, yaw and orientation ────────────────────────── */
for (let i = 0; i < 36; i++) {
  const heading = i * 10;
  vectors.heading.push({ headingDeg: heading, yawRad: round(geo.headingToYaw(heading)) });
  const q = geo.headingToQuaternion(heading);
  vectors.quaternion.push({
    headingDeg: heading,
    quaternion: mapValues(q, round),
    back: round(geo.headingFromQuaternion(q))
  });
}

/* ── distance ─────────────────────────────────────────────── */
for (let i = 0; i < PLACES.length; i++) {
  for (let j = i + 1; j < PLACES.length; j++) {
    vectors.distance.push({
      a: PLACES[i], b: PLACES[j],
      metres: round(geo.haversine(PLACES[i].lat, PLACES[i].lon, PLACES[j].lat, PLACES[j].lon))
    });
  }
}

/* ── geohash ──────────────────────────────────────────────── */
const HASHES = [
  { lat: 57.64911, lon: 10.40744, precision: 11 },
  { lat: 0, lon: 0, precision: 6 },
  { lat: -90, lon: -180, precision: 8 },
  { lat: 90, lon: 180, precision: 8 }
];
for (const p of PLACES) { HASHES.push({ lat: p.lat, lon: p.lon, precision: 10 }); }
for (const h of HASHES) {
  vectors.geohash.push({ ...h, hash: geo.geohash(h.lat, h.lon, h.precision) });
}

for (const radiusM of [5, 50, 200, 1000, 5000]) {
  for (const p of PLACES.slice(0, 4)) {
    vectors.bounds.push({
      lat: p.lat, lon: p.lon, radiusM,
      precision: geo.geohashPrecisionFor(radiusM),
      ranges: geo.geohashQueryBounds(p.lat, p.lon, radiusM)
    });
  }
}

/* ── the localization frame ───────────────────────────────── */
for (const origin of PLACES.slice(0, 5)) {
  for (const headingDeg of [0, 37, 90, 180, 271, 359]) {
    const frame = localize.makeFrame(
      { position: origin, headingDeg, accuracy: { positionM: 5, headingDeg: 10 } },
      { position: { x: between(-20, 20), y: 0, z: between(-20, 20) }, yawDeg: 0 }
    );

    const samples = [];
    for (let i = 0; i < 4; i++) {
      const target = {
        lat: clampLat(origin.lat + between(-0.005, 0.005)),
        lon: wrapLon(origin.lon + between(-0.005, 0.005)),
        h: origin.h + between(-10, 10)
      };
      const local = frame.toLocal(target);
      samples.push({
        target,
        local: mapValues(local, round),
        back: mapValues(frame.toGlobal(local), round)
      });
    }

    vectors.frame.push({
      origin,
      headingDeg,
      offset: mapValues(frame.toLocal(origin), round),
      samples
    });
  }
}

/* ── heading from a walked baseline ───────────────────────── */
const BASE = { lat: 51.5007, lon: -0.1246 };
const shift = (dn, de) => ({
  lat: BASE.lat + (dn / 6371008.8) * 180 / Math.PI,
  lon: BASE.lon + (de / (6371008.8 * Math.cos(BASE.lat * Math.PI / 180))) * 180 / Math.PI
});

const WALKS = [
  { name: 'north, tracked forward', a: [0, 0, 0, 0], b: [30, 0, 0, -30], accuracy: 1 },
  { name: 'east, tracked forward', a: [0, 0, 0, 0], b: [0, 30, 0, -30], accuracy: 1 },
  { name: 'north, tracked sideways', a: [0, 0, 0, 0], b: [30, 0, 30, 0], accuracy: 1 },
  { name: 'too short for the noise', a: [0, 0, 0, 0], b: [3, 0, 0, -3], accuracy: 1 },
  { name: 'swamped by a poor fix', a: [0, 0, 0, 0], b: [30, 0, 0, -30], accuracy: 20 },
  { name: 'session never saw the walk', a: [0, 0, 0, 0], b: [30, 0, 0, 0], accuracy: 1 },
  { name: 'session moved further than the walk', a: [0, 0, 0, 0], b: [30, 0, 0, -200], accuracy: 1 },
  { name: 'long baseline', a: [0, 0, 0, 0], b: [120, 0, 0, -120], accuracy: 2 }
];

for (const walk of WALKS) {
  const make = ([dn, de, lx, lz]) => ({
    position: shift(dn, de),
    accuracy: { positionM: walk.accuracy },
    local: { x: lx, y: 0, z: lz }
  });
  const a = make(walk.a);
  const b = make(walk.b);
  const result = localize.headingFromBaseline(a, b);

  vectors.baseline.push({
    name: walk.name,
    a: { position: a.position, accuracy: a.accuracy, local: a.local },
    b: { position: b.position, accuracy: b.accuracy, local: b.local },
    result: result === null ? null : {
      headingDeg: round(result.headingDeg),
      sessionYawDeg: result.sessionYawDeg === null ? null : round(result.sessionYawDeg),
      separationM: round(result.separationM),
      accuracyDeg: round(result.accuracyDeg)
    }
  });
}

/* ── the origin, estimated from every fix ─────────────────── */
const ORIGIN_CASES = [
  { name: 'a single fix is used as it stands', yaw: 0, n: 1, spread: 8, sigma: 6 },
  { name: 'standing still, fixes wobbling', yaw: 0, n: 6, spread: 8, sigma: 6 },
  { name: 'walking, tracked', yaw: 0, n: 6, spread: 8, sigma: 5, walk: 12 },
  { name: 'session yawed east', yaw: 90, n: 6, spread: 10, sigma: 5, walk: 10 },
  { name: 'session yawed south west', yaw: 214, n: 8, spread: 12, sigma: 7, walk: 8 },
  { name: 'wildly different accuracies', yaw: 33, n: 6, spread: 20, sigma: 3, vary: true },
  { name: 'southern hemisphere', yaw: 120, n: 5, spread: 9, sigma: 5, walk: 6,
    base: { lat: -33.8568, lon: 151.2153 } },
  { name: 'high latitude', yaw: 300, n: 5, spread: 9, sigma: 5, walk: 6,
    base: { lat: 78.2232, lon: 15.6267 } }
];

for (const c of ORIGIN_CASES) {
  const base = c.base || { lat: 51.5007, lon: -0.1246 };
  const samples = [];

  for (let i = 0; i < c.n; i++) {
    const dn = between(-c.spread, c.spread) + (c.walk ? i * c.walk : 0);
    const de = between(-c.spread, c.spread);
    samples.push({
      position: {
        lat: base.lat + (dn / 6371008.8) * 180 / Math.PI,
        lon: base.lon + (de / (6371008.8 * Math.cos(base.lat * Math.PI / 180))) * 180 / Math.PI,
        h: between(-5, 5)
      },
      accuracy: { positionM: c.vary ? Math.max(1, c.sigma * (1 + i * 3)) : c.sigma },
      local: {
        x: between(-3, 3),
        y: between(-1, 1),
        z: c.walk ? -i * c.walk : between(-3, 3)
      }
    });
  }

  const estimated = localize.estimateOrigin(samples, c.yaw);
  vectors.origin.push({
    name: c.name,
    sessionYawDeg: c.yaw,
    samples: samples.map((s) => ({
      position: mapValues(s.position, round),
      accuracy: s.accuracy,
      local: mapValues(s.local, round)
    })),
    origin: mapValues(estimated, round),
    accuracyM: round(localize.originAccuracy(samples))
  });
}

function mapValues(obj, fn) {
  const out = {};
  for (const key of Object.keys(obj)) { out[key] = fn(obj[key]); }
  return out;
}
function clampLat(v) { return Math.max(-89.9, Math.min(89.9, v)); }
function wrapLon(v) { return ((v + 540) % 360) - 180; }

await mkdir(join(ROOT, 'native', 'vectors'), { recursive: true });
const out = join(ROOT, 'native', 'vectors', 'core.json');
await writeFile(out, JSON.stringify(vectors, null, 1));

const count = Object.values(vectors).filter(Array.isArray).reduce((n, v) => n + v.length, 0);
console.log(`wrote ${out} — ${count} cases`);
