using System;
using System.Collections.Generic;

namespace MarkerOne.Core
{
    /// <summary>
    /// Geodesy for placing things in the world.
    ///
    /// Everything stored is in one global frame — WGS84 latitude, longitude and
    /// height, plus an orientation expressed in the local East-North-Up frame at
    /// that point. Whatever localises the device only has to report a pose in
    /// that same frame, and content placed by one provider is readable by
    /// another.
    ///
    /// A direct port of spatial/geo.js, checked against vectors generated by it.
    /// Two sign errors have lived in that file's history — a mirrored render
    /// frame and a quaternion facing backwards — and neither announced itself
    /// as anything except the world being subtly wrong. Hence the vectors.
    /// </summary>
    public static class Geodesy
    {
        // WGS84
        public const double A = 6378137.0;                  // semi-major axis, metres
        public const double F = 1 / 298.257223563;          // flattening
        public static readonly double E2 = F * (2 - F);     // first eccentricity squared

        public const double EarthMeanRadius = 6371008.8;

        private const double D2R = Math.PI / 180.0;
        private const double R2D = 180.0 / Math.PI;

        // ── the ellipsoid ────────────────────────────────────────

        public static Ecef ToEcef(GeoPoint p)
        {
            double sinLat = Math.Sin(p.Lat * D2R);
            double cosLat = Math.Cos(p.Lat * D2R);
            double sinLon = Math.Sin(p.Lon * D2R);
            double cosLon = Math.Cos(p.Lon * D2R);
            double n = A / Math.Sqrt(1 - E2 * sinLat * sinLat);

            return new Ecef(
                (n + p.Height) * cosLat * cosLon,
                (n + p.Height) * cosLat * sinLon,
                (n * (1 - E2) + p.Height) * sinLat);
        }

        /// <summary>Bowring's method, iterated. Converges in two or three
        /// passes for any height a phone will ever be at.</summary>
        public static GeoPoint FromEcef(Ecef e)
        {
            double lon = Math.Atan2(e.Y, e.X);
            double p = Math.Sqrt(e.X * e.X + e.Y * e.Y);
            double lat = Math.Atan2(e.Z, p * (1 - E2));

            double n = A;
            for (int i = 0; i < 5; i++)
            {
                double sinLat = Math.Sin(lat);
                n = A / Math.Sqrt(1 - E2 * sinLat * sinLat);
                lat = Math.Atan2(e.Z + E2 * n * sinLat, p);
            }

            return new GeoPoint(lat * R2D, lon * R2D, p / Math.Cos(lat) - n);
        }

        // ── local tangent plane ──────────────────────────────────

        /// <summary>Metres east, north and up from an origin. Over the few
        /// hundred metres an AR session spans this is flat enough to treat as
        /// Cartesian, which is what makes it the bridge to a render frame.
        /// </summary>
        public static Enu ToEnu(GeoPoint point, GeoPoint origin)
        {
            Ecef p = ToEcef(point);
            Ecef o = ToEcef(origin);

            double dx = p.X - o.X;
            double dy = p.Y - o.Y;
            double dz = p.Z - o.Z;

            double sinLat = Math.Sin(origin.Lat * D2R);
            double cosLat = Math.Cos(origin.Lat * D2R);
            double sinLon = Math.Sin(origin.Lon * D2R);
            double cosLon = Math.Cos(origin.Lon * D2R);

            return new Enu(
                -sinLon * dx + cosLon * dy,
                -sinLat * cosLon * dx - sinLat * sinLon * dy + cosLat * dz,
                cosLat * cosLon * dx + cosLat * sinLon * dy + sinLat * dz);
        }

        public static GeoPoint FromEnu(Enu enu, GeoPoint origin)
        {
            Ecef o = ToEcef(origin);

            double sinLat = Math.Sin(origin.Lat * D2R);
            double cosLat = Math.Cos(origin.Lat * D2R);
            double sinLon = Math.Sin(origin.Lon * D2R);
            double cosLon = Math.Cos(origin.Lon * D2R);

            return FromEcef(new Ecef(
                o.X - sinLon * enu.East - sinLat * cosLon * enu.North + cosLat * cosLon * enu.Up,
                o.Y + cosLon * enu.East - sinLat * sinLon * enu.North + cosLat * sinLon * enu.Up,
                o.Z + cosLat * enu.North + sinLat * enu.Up));
        }

        // ── render frame ─────────────────────────────────────────

        /// <summary>Unity, three.js and WebXR are all Y-up, right-handed, with
        /// -Z forward. Mapping East to +X and Up to +Y leaves North on -Z.
        /// Getting this backwards puts the world 180 degrees out, which looks
        /// exactly like a compass error and is not one.</summary>
        public static Vec3 EnuToRender(Enu enu) => new Vec3(enu.East, enu.Up, -enu.North);

        public static Enu RenderToEnu(Vec3 v) => new Enu(v.X, -v.Z, v.Y);

        /// <summary>A yaw measured clockwise from north — what every compass and
        /// every geospatial API reports — as a rotation about the render
        /// frame's Y axis, which runs anticlockwise seen from above.</summary>
        public static double HeadingToYaw(double degreesFromNorth) => -degreesFromNorth * D2R;

        // ── orientation ──────────────────────────────────────────

        /// <summary>Placements store a full quaternion in the ENU basis — X
        /// east, Y north, Z up — with an object's own forward taken as +Y. Only
        /// the yaw is meaningful for content standing on the ground.</summary>
        public static Quat HeadingToQuaternion(double headingDeg)
        {
            double half = -headingDeg * D2R / 2;
            return new Quat(0, 0, Math.Sin(half), Math.Cos(half));
        }

        public static double HeadingFromQuaternion(Quat q)
        {
            Vec3 v = Rotate(q, new Vec3(0, 1, 0));
            return (Math.Atan2(v.X, v.Y) * R2D + 360) % 360;
        }

        public static Vec3 Rotate(Quat q, Vec3 v)
        {
            double tx = 2 * (q.Y * v.Z - q.Z * v.Y);
            double ty = 2 * (q.Z * v.X - q.X * v.Z);
            double tz = 2 * (q.X * v.Y - q.Y * v.X);

            return new Vec3(
                v.X + q.W * tx + (q.Y * tz - q.Z * ty),
                v.Y + q.W * ty + (q.Z * tx - q.X * tz),
                v.Z + q.W * tz + (q.X * ty - q.Y * tx));
        }

        // ── distance ─────────────────────────────────────────────

        public static double Haversine(double latA, double lonA, double latB, double lonB)
        {
            double dLat = (latB - latA) * D2R;
            double dLon = (lonB - lonA) * D2R;
            double s = Math.Sin(dLat / 2) * Math.Sin(dLat / 2) +
                       Math.Cos(latA * D2R) * Math.Cos(latB * D2R) *
                       Math.Sin(dLon / 2) * Math.Sin(dLon / 2);
            return 2 * EarthMeanRadius * Math.Asin(Math.Min(1, Math.Sqrt(s)));
        }

        public static double Haversine(GeoPoint a, GeoPoint b) =>
            Haversine(a.Lat, a.Lon, b.Lat, b.Lon);

        // ── geohash ──────────────────────────────────────────────

        private const string Base32 = "0123456789bcdefghjkmnpqrstuvwxyz";

        /// <summary>Firestore has no geospatial index. The standard workaround:
        /// interleave latitude and longitude bits into one sortable string, so
        /// a box on the globe becomes a handful of string ranges.</summary>
        public static string Geohash(double lat, double lon, int precision = 10)
        {
            double latLo = -90, latHi = 90, lonLo = -180, lonHi = 180;
            var hash = new System.Text.StringBuilder(precision);
            int bits = 0, bit = 0;
            bool even = true;

            while (hash.Length < precision)
            {
                if (even)
                {
                    double mid = (lonLo + lonHi) / 2;
                    // Values sitting exactly on the midpoint go up, which is why
                    // the canonical hash of (0,0) is "s000..." and not "7zzz...".
                    if (lon >= mid) { bits = (bits << 1) + 1; lonLo = mid; }
                    else { bits <<= 1; lonHi = mid; }
                }
                else
                {
                    double mid = (latLo + latHi) / 2;
                    if (lat >= mid) { bits = (bits << 1) + 1; latLo = mid; }
                    else { bits <<= 1; latHi = mid; }
                }

                even = !even;
                if (++bit == 5)
                {
                    hash.Append(Base32[bits]);
                    bit = 0;
                    bits = 0;
                }
            }

            return hash.ToString();
        }

        private static readonly double[] CellWidth =
        {
            5009400, 1252300, 156500, 39100, 4900, 1220, 152.9, 38.2, 4.8, 1.2, 0.149
        };

        public static int GeohashPrecisionFor(double radiusM)
        {
            for (int i = CellWidth.Length - 1; i > 0; i--)
            {
                if (CellWidth[i] >= radiusM) { return i; }
            }
            return 1;
        }

        /// <summary>The ranges covering a circle. Neighbouring cells are needed
        /// because the circle almost never sits inside one — querying only the
        /// centre's own cell silently loses anything near its edge, which is
        /// most things.</summary>
        public static List<(string Start, string End)> GeohashQueryBounds(
            double lat, double lon, double radiusM)
        {
            int precision = GeohashPrecisionFor(radiusM);

            double dLat = (radiusM / EarthMeanRadius) * R2D;
            double cos = Math.Cos(lat * D2R);
            double dLon = Math.Abs(cos) < 1e-6 ? 180 : (radiusM / (EarthMeanRadius * cos)) * R2D;

            var seen = new HashSet<string>();
            var ranges = new List<(string, string)>();

            for (int i = -1; i <= 1; i++)
            {
                for (int j = -1; j <= 1; j++)
                {
                    double y = ClampLat(lat + i * dLat);
                    double x = WrapLon(lon + j * dLon);
                    string cell = Geohash(y, x, precision);
                    if (!seen.Add(cell)) { continue; }
                    // '~' sorts above every base32 character, so [cell, cell~]
                    // is "every hash starting with this prefix".
                    ranges.Add((cell, cell + "~"));
                }
            }

            return ranges;
        }

        private static double ClampLat(double lat) => Math.Max(-90, Math.Min(90, lat));

        private static double WrapLon(double lon)
        {
            while (lon > 180) { lon -= 360; }
            while (lon < -180) { lon += 360; }
            return lon;
        }
    }
}
